2019-10-11 14:11:18.599 [error] <0.237.0> gen_server <0.237.0> terminated with reason: {socket_error,timeout}
2019-10-11 14:11:18.600 [error] <0.231.0> gen_server <0.231.0> terminated with reason: {socket_error,timeout}
2019-10-11 14:11:18.613 [error] <0.231.0> CRASH REPORT Process <0.231.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-10-11 14:11:18.613 [error] <0.229.0> Supervisor {<0.229.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.230.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.231.0> exit with reason {socket_error,timeout} in context child_terminated
2019-10-11 14:11:18.613 [error] <0.229.0> Supervisor {<0.229.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.230.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.231.0> exit with reason reached_max_restart_intensity in context shutdown
